package com.pursuit.noteblog.dao;

import com.pursuit.noteblog.po.NoteUser;
import com.pursuit.noteblog.po.NoteUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int countByExample(NoteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int deleteByExample(NoteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int insert(NoteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int insertSelective(NoteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    List<NoteUser> selectByExample(NoteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    NoteUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteUser record, @Param("example") NoteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteUser record, @Param("example") NoteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteUser record);
}