package com.pursuit.noteblog.dao;

import com.pursuit.noteblog.po.NoteContent;
import com.pursuit.noteblog.po.NoteContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int countByExample(NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int deleteByExample(NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int insert(NoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int insertSelective(NoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    List<NoteContent> selectByExampleWithBLOBs(NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    List<NoteContent> selectByExample(NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    NoteContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteContent record, @Param("example") NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") NoteContent record, @Param("example") NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteContent record, @Param("example") NoteContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteContent record);
}