package com.pursuit.noteblog.dao;

import com.pursuit.noteblog.po.NoteConfig;
import com.pursuit.noteblog.po.NoteConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int countByExample(NoteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int deleteByExample(NoteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int insert(NoteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int insertSelective(NoteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    List<NoteConfig> selectByExample(NoteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    NoteConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteConfig record, @Param("example") NoteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteConfig record, @Param("example") NoteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteConfig record);
}