package com.pursuit.noteblog.dao;

import com.pursuit.noteblog.po.NoteSummary;
import com.pursuit.noteblog.po.NoteSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int countByExample(NoteSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int deleteByExample(NoteSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int insert(NoteSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int insertSelective(NoteSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    List<NoteSummary> selectByExample(NoteSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    NoteSummary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteSummary record, @Param("example") NoteSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteSummary record, @Param("example") NoteSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteSummary record);
}