package com.pursuit.noteblog.dao;

import com.pursuit.noteblog.po.NoteBook;
import com.pursuit.noteblog.po.NoteBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int countByExample(NoteBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int deleteByExample(NoteBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int insert(NoteBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int insertSelective(NoteBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    List<NoteBook> selectByExample(NoteBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    NoteBook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoteBook record, @Param("example") NoteBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoteBook record, @Param("example") NoteBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoteBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoteBook record);
}